#!/system/bin/sh
# Created by HadiK
USB_PLUG=`cat /sys/class/power_supply/usb/online`;
    if [ $USB_PLUG = "1" ]; then
    mount -t rootfs -o remount,rw rootfs
    echo "Executed By System" >/sbin/.lpm.system
    mount -o remount,rw /data
    mount -o remount,rw /system
    sleep 2
    cd /system/lib
    exec lpm
	fi;
# Done