#!/system/bin/sh
mount -t rootfs -o remount,rw rootfs
echo "Executed" >/sbin/.efs
sleep 1
mount -o rw,remount rootfs /
mount -o rw,remount /system
/system/xbin/busybox losetup /dev/block/loop4 /system/vendor/vandroids4ptx/efs.img
mount -o rw -t ext4 /dev/block/loop4 /efs
if [ ! -e /data/misc/bluetooth/btmac.txt ];
then
mount -o rw,remount /efs;
cp /efs/bluetooth/bt_addr /efs/bluetooth/btmac.txt;
cp /efs/bluetooth/btmac.txt /data/misc/bluetooth/btmac.txt;
chmod 660 /data/misc/bluetooth/btmac.txt;
cp /data/misc/bluetooth/btmac.txt /productinfo/btmac.txt;
chmod 660 /productinfo/btmac.txt;
cp /efs/wifi/.mac.info /efs/wifi/wifimac.txt;
cp /efs/wifi/wifimac.txt /data/misc/wifi/wifimac.txt;
chmod 660 /data/misc/wifi/wifimac.txt;
cp /data/misc/wifi/wifimac.txt /productinfo/wifimac.txt;
chmod 660 /productinfo/wifimac.txt;
else
echo "off" >/productinfo/sysdump_flag;
fi;

sh /sbin/intextSdCard