ifneq ($(TARGET_PREBUILT_KERNEL),)
## PREBUILT KERNEL MODULES
# SET KERNEL MODULE PATH
ifeq ($(INSTALL_KERNEL_MODULES_ON_RAMDISK),true)
KMODULE_PATH := $(TARGET_ROOT_OUT)/lib/modules
else
KMODULE_PATH := $(OUT)/system/lib/modules
endif # INSTALL_KERNEL_MODULES_ON_RAMDISK

include $(CLEAR_VARS)
LOCAL_MODULE := autotst.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(KMODULE_PATH)
LOCAL_SRC_FILES := modules/autotst.ko
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gator.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(KMODULE_PATH)
LOCAL_SRC_FILES := modules/gator.ko
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mali.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(KMODULE_PATH)
LOCAL_SRC_FILES := modules/mali.ko
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mmc_test.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(KMODULE_PATH)
LOCAL_SRC_FILES := modules/mmc_test.ko
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := sprdwl.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(KMODULE_PATH)
LOCAL_SRC_FILES := modules/sprdwl.ko
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := trout_fm.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(KMODULE_PATH)
LOCAL_SRC_FILES := modules/trout_fm.ko
include $(BUILD_PREBUILT)
endif #
